/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  NativeEventEmitter,
  NativeModules,
} from 'react-native';
import {ad} from 'react-native-ad';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };

  componentDidMount() {
    ad.init({
      appid: '5016582',
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆广告 example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <TouchableOpacity
          style={{
            marginVertical: 20,
            paddingHorizontal: 30,
            paddingVertical: 15,
            backgroundColor: '#F96',
            borderRadius: 50,
          }}
          onPress={() => {
            const splashAd = ad.startSplash('5016582', '816582039');

            splashAd.subscribe('onAdTimeOver', event => {
              console.log('广告时间结束监听', event);
            });

            splashAd.subscribe('onAdSkip', i => {
              console.log('用户点击跳过监听', i);
            });

            splashAd.subscribe('onError', e => {
              console.log('开屏加载失败监听', e);
            });

            // const a = 'onAdTimeOver';
            // const { BytedADSplash } = NativeModules;

            // const event = new NativeEventEmitter(BytedADSplash);
            // event.addListener('TTSplashAdListener', reminder => {
            //   console.log(reminder);
            //   if (reminder[a]) {
            //     console.log(a, reminder[a]);
            //   }
            // });
          }}>
          <Text style={{textAlign: 'center'}}>开屏广告</Text>
        </TouchableOpacity>

        <ad.Feed
          codeId="916582486" // 广告位 codeid （必传），注意区分 Android 和 IOS
          visible={true}
          adWidth={200}
          onLoad={smg => {
            // 广告加载成功回调
            console.log('头条 Feed 广告加载成功！', smg);
          }}
          onError={err => {
            // 广告加载失败回调
            console.log('头条 Feed 广告加载失败！', err);
          }}
          onClick={val => {
            // 广告点击回调
            console.log('头条 Feed 广告被用户点击！', val);
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
