/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  NativeEventEmitter,
  NativeModules,
} from 'react-native';
import {ad} from 'react-native-ad';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆广告 example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <TouchableOpacity
          style={{
            marginVertical: 20,
            paddingHorizontal: 30,
            paddingVertical: 15,
            backgroundColor: '#F96',
            borderRadius: 50,
          }}
          onPress={() => {
            const splashAd = ad.startSplash({
              appid: '5016582',
              codeid: '816582039',
            });

            // const splashAd = ad.startSplash({
            //   provider: '腾讯',
            //   appid: '1110154564',
            //   codeid: '3090393544429091',
            // });

            splashAd.subscribe('onAdClose', event => {
              console.log('广告关闭', event);
            });

            splashAd.subscribe('onAdSkip', i => {
              console.log('用户点击跳过监听', i);
            });

            splashAd.subscribe('onAdError', e => {
              console.log('开屏加载失败监听', e);
            });

            splashAd.subscribe('onAdClick', e => {
              console.log('开屏被用户点击了', e);
            });

            splashAd.subscribe('onAdShow', e => {
              console.log('开屏开始展示', e);
            });
          }}>
          <Text style={{textAlign: 'center'}}>开屏广告</Text>
        </TouchableOpacity>

        <ad.Feed
          codeId="916582486" // 广告位 codeid （必传），注意区分 Android 和 IOS
          visible={true}
          adWidth={200}
          onLoad={smg => {
            // 广告加载成功回调
            console.log('头条 Feed 广告加载成功！', smg);
          }}
          onError={err => {
            // 广告加载失败回调
            console.log('头条 Feed 广告加载失败！', err);
          }}
          onClick={val => {
            // 广告点击回调
            console.log('头条 Feed 广告被用户点击！', val);
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
